ZIP_FILE_URL = 'http://tamaraberg.com/faceDataset/faceData.tar.gz'
ZIP_FILE_PATH = 'faces_in_the_wild_dataset/faceData.tar.gz'
UNZIPPED_FILE_PATH = './faces_in_the_wild/'
DIR_NAME= 'faceData/'
MAT_FILE = './faces_in_the_wild/faceData/FacesInTheWild.mat'
SAVE_IMG_DIR='./img/'
IMG_DICT_PICKLE_PATH='./dump/img_dict.p'
